# This is the content for your NEW file at:
# backend/app/models/code_component.py

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import JSONB

from app.db.base_class import Base

class CodeComponent(Base):
    """
    Database model for storing code component metadata.
    This represents a reference to a piece of code, like a file,
    class, function, or entire repository.
    """
    __tablename__ = "code_components"

    id = Column(Integer, primary_key=True, index=True)
    
    # A user-friendly name for the component
    name = Column(String, index=True, nullable=False)
    
    # The type of component, e.g., "Repository", "File", "Class", "Function"
    component_type = Column(String, nullable=False)

    # A URL or path to the code, e.g., a GitHub URL or a file path
    location = Column(String, nullable=False)
    
    # The version of the code component, e.g., a git commit hash or a version tag
    version = Column(String, nullable=False)
    
    # A high-level, human-readable summary of the code's purpose, generated by AI.
    summary = Column(Text, nullable=True)
    
    # Structured data from the analysis, e.g., list of functions, classes, dependencies.
    # Stored as a flexible JSONB object for efficient querying.
    structured_analysis = Column(JSONB, nullable=True)
    
    # The status of the background analysis job. This is critical for the frontend
    # to track progress and handle failures.
    analysis_status = Column(String, default="pending", index=True, nullable=False) # "pending", "processing", "completed", "failed"
   
    # The timestamp when the code component was registered in the system
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # The timestamp when the code component was updated in the system
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Foreign key to link this component to the user who registered it
    owner_id = Column(Integer, ForeignKey("users.id"))
    
    # Creates a relationship to the User model
    owner = relationship("User")

