from typing import TYPE_CHECKING, List
from datetime import datetime
from sqlalchemy import Integer, String, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base

if TYPE_CHECKING:
    from .user import User  # noqa: F401
    from .task import Task  # noqa: F401
    from .repository import Repository  # noqa: F401

class CodeComponent(Base):
    """
    Database model for storing code component metadata.
    This represents a reference to a piece of code, like a file,
    class, function, or entire repository.

    SPRINT 3: Added repository_id to link files back to their parent repository.
    """
    __tablename__ = "code_components"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    tenant_id: Mapped[int] = mapped_column(Integer, default=1, nullable=False, index=True)  # Multi-tenancy support

    # A user-friendly name for the component
    name: Mapped[str] = mapped_column(String, index=True, nullable=False)

    # The type of component, e.g., "Repository", "File", "Class", "Function"
    component_type: Mapped[str] = mapped_column(String, nullable=False)

    # A URL or path to the code, e.g., a GitHub URL or a file path
    location: Mapped[str] = mapped_column(String, nullable=False)

    # The version of the code component, e.g., a git commit hash or a version tag
    version: Mapped[str] = mapped_column(String, nullable=False)

    # A high-level, human-readable summary of the code's purpose, generated by AI.
    summary: Mapped[str] = mapped_column(Text, nullable=True)

    # Structured data from the analysis, e.g., list of functions, classes, dependencies.
    structured_analysis: Mapped[dict] = mapped_column(JSON, nullable=True)

    # SPRINT 3 Day 5: Delta analysis fields
    # Stores the diff between current and previous analysis (added/removed/modified)
    analysis_delta: Mapped[dict] = mapped_column(JSON, nullable=True)
    # Hash of previous structured_analysis — used to detect whether re-analysis is needed
    previous_analysis_hash: Mapped[str] = mapped_column(String(64), nullable=True)

    # The status of the background analysis job.
    analysis_status: Mapped[str] = mapped_column(String, default="pending", index=True, nullable=False)

    # Foreign key to link this component to the user who registered it
    owner_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id"))

    # SPRINT 3: Link to parent repository (nullable for standalone components)
    repository_id: Mapped[int] = mapped_column(Integer, ForeignKey("repositories.id"), nullable=True, index=True)
    
    # Relationships
    owner: Mapped["User"] = relationship("User")
    repository: Mapped["Repository"] = relationship("Repository", foreign_keys=[repository_id])

    # Timestamp fields
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now, onupdate=datetime.now, nullable=False)

    # Sprint 2 Extended - Phase 10: Tasks linked to this code component
    tasks: Mapped[List["Task"]] = relationship(
        "Task", back_populates="code_component", lazy="dynamic"
    )

