services:
  app:
    container_name: dokydoc_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/dokydoc
      - PYTHONPATH=/app
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000  # Removed --reload

  db:
    image: postgres:15-alpine
    container_name: dokydoc_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=dokydoc
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: