"""
P5C-05: TestSuiteService — generates downloadable pytest test files from BRD atoms.

Atoms classified as "static" or "runtime" testability get test functions generated by Gemini.
Tests are grouped into files by atom_type and returned as an in-memory zip.
"""
import io
import asyncio
import zipfile
from datetime import datetime
from sqlalchemy.orm import Session
from app.core.logging import get_logger
from app.models.requirement_atom import RequirementAtom

logger = get_logger("test_suite_service")

# Group atom types into test files
_FILE_GROUPS = {
    "test_contracts.py": ["API_CONTRACT", "INTEGRATION_POINT"],
    "test_business_rules.py": ["BUSINESS_RULE", "DATA_CONSTRAINT"],
    "test_functional.py": ["FUNCTIONAL_REQUIREMENT", "WORKFLOW_STEP"],
    "test_security.py": ["SECURITY_REQUIREMENT"],
    "test_error_handling.py": ["ERROR_SCENARIO"],
    "test_nfr.py": ["NFR"],
}

_FILE_HEADER = '''"""
Auto-generated test suite by DokyDoc.
Document: {doc_title}
Generated: {generated_at}
WARNING: Review before running. These tests are AI-generated from BRD requirements.
"""
import os
import time
import pytest
import httpx

BASE_URL = os.getenv("APP_BASE_URL", "http://localhost:8000")
AUTH_TOKEN = os.getenv("TEST_AUTH_TOKEN", "")

HEADERS = {{"Authorization": f"Bearer {{AUTH_TOKEN}}"}}
'''

_CONFTEST = '''"""
Shared fixtures for DokyDoc auto-generated test suite.
"""
import os
import pytest
import httpx

BASE_URL = os.getenv("APP_BASE_URL", "http://localhost:8000")
AUTH_TOKEN = os.getenv("TEST_AUTH_TOKEN", "")


@pytest.fixture
def client():
    with httpx.Client(base_url=BASE_URL, headers={"Authorization": f"Bearer {AUTH_TOKEN}"}) as c:
        yield c


@pytest.fixture
def auth_headers():
    return {"Authorization": f"Bearer {AUTH_TOKEN}"}
'''

_PYTEST_INI = """[pytest]
markers =
    integration: marks tests as integration tests (require running app)
    slow: marks tests as slow (performance tests)
testpaths = dokydoc_tests
"""


class TestSuiteService:

    async def generate_zip(
        self,
        db: Session,
        *,
        document_id: int,
        tenant_id: int,
        doc_title: str,
    ) -> bytes:
        """
        Generate all test files and return as a zip bytes object.
        Calls Gemini for each testable atom. Placeholder inserted on Gemini failure.
        """
        from app.services.ai.gemini import call_gemini_for_test_generation

        atoms = db.query(RequirementAtom).filter(
            RequirementAtom.document_id == document_id,
            RequirementAtom.tenant_id == tenant_id,
            RequirementAtom.testability.in_(["static", "runtime"]),
        ).all()

        if not atoms:
            buf = io.BytesIO()
            with zipfile.ZipFile(buf, "w") as zf:
                zf.writestr("README.txt", "No auto-testable atoms found in this document.")
            return buf.getvalue()

        type_to_file: dict[str, str] = {}
        for filename, types in _FILE_GROUPS.items():
            for t in types:
                type_to_file[t] = filename

        file_contents: dict[str, list[str]] = {k: [] for k in _FILE_GROUPS}
        generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        for atom in atoms:
            target_file = type_to_file.get(atom.atom_type, "test_functional.py")
            try:
                test_code = await call_gemini_for_test_generation({
                    "atom_id": atom.atom_id,
                    "atom_type": atom.atom_type,
                    "content": atom.content,
                    "criticality": atom.criticality or "standard",
                    "testability": atom.testability or "static",
                })
                file_contents[target_file].append(f"\n\n{test_code}")
            except Exception as e:
                logger.warning(f"Test generation failed for atom {atom.atom_id}: {e}")
                snake = atom.atom_id.lower().replace("-", "_")
                file_contents[target_file].append(
                    f'\n\n@pytest.mark.skip(reason="AI generation failed")\n'
                    f'def test_{snake}_placeholder():\n'
                    f'    """BRD requirement: {atom.content[:100]}"""\n'
                    f'    pass\n'
                )

        buf = io.BytesIO()
        header_fmt = _FILE_HEADER.format(doc_title=doc_title, generated_at=generated_at)
        with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for filename, functions in file_contents.items():
                if not functions:
                    continue
                content = header_fmt + "".join(functions)
                zf.writestr(f"dokydoc_tests/{filename}", content)
            zf.writestr("dokydoc_tests/conftest.py", _CONFTEST)
            zf.writestr("pytest.ini", _PYTEST_INI)

        return buf.getvalue()


    def generate_zip_sync(
        self,
        db: Session,
        *,
        document_id: int,
        tenant_id: int,
        doc_title: str,
    ) -> bytes:
        """Synchronous wrapper for Celery tasks (BUG-04 fix)."""
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            return loop.run_until_complete(
                self.generate_zip(
                    db=db,
                    document_id=document_id,
                    tenant_id=tenant_id,
                    doc_title=doc_title,
                )
            )
        finally:
            loop.close()
            asyncio.set_event_loop(None)


test_suite_service = TestSuiteService()
