"""initial_schema — no-op placeholder

Revision ID: fc8619cf3d6f
Revises:
Create Date: 2026-04-24

This revision was auto-generated by 'alembic revision --autogenerate' against
an existing database. The tables and indexes it would have described are
already managed by the sprint-numbered migration chain (c8f2a1d9e321 and
onwards). This file is kept as a no-op so Alembic can track the revision ID
and include it in the merge migration without attempting destructive DDL.
"""
from alembic import op

revision = 'fc8619cf3d6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
