"""Add document table

Revision ID: 1fc7da2618bf
Revises: 50074aed9429
Create Date: 2025-06-26 18:41:54.304210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc7da2618bf'
down_revision = '50074aed9429'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
