"""Add document_code_links table

Revision ID: 30a181807d1e
Revises: 7010711a60bd
Create Date: 2025-06-29 15:16:57.766780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a181807d1e'
down_revision = '7010711a60bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
