"""Add document_code_links table

Revision ID: 7010711a60bd
Revises: b6e3ef4784d5
Create Date: 2025-06-29 15:14:21.674480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7010711a60bd'
down_revision = 'b6e3ef4784d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
