"""Add status and progress to documents

Revision ID: 7f9f4bbc8fcd
Revises: 1032a3c5bd70
Create Date: 2025-07-07 13:21:15.433269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9f4bbc8fcd'
down_revision = '1032a3c5bd70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
