"""Add progress field to Document

Revision ID: 9a7071df697a
Revises: d48bf977548d
Create Date: 2025-07-07 14:04:10.906735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7071df697a'
down_revision = 'd48bf977548d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'progress')
    # ### end Alembic commands ###
