"""Add code_components table

Revision ID: b6e3ef4784d5
Revises: 1fc7da2618bf
Create Date: 2025-06-29 10:12:06.330458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e3ef4784d5'
down_revision = '1fc7da2618bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
