"""Add content and size columns to documents

Revision ID: cdf6191b409e
Revises: 30a181807d1e
Create Date: 2025-07-02 17:11:32.518489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf6191b409e'
down_revision = '30a181807d1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size_kb', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content')
    op.drop_column('documents', 'file_size_kb')
    # ### end Alembic commands ###
