"""Add progress column to documents

Revision ID: d48bf977548d
Revises: 7f9f4bbc8fcd
Create Date: 2025-07-07 13:54:09.456295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48bf977548d'
down_revision = '7f9f4bbc8fcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
