"""Add content and size columns to documents

Revision ID: d6dc7e28da21
Revises: cdf6191b409e
Create Date: 2025-07-02 17:21:11.405568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dc7e28da21'
down_revision = 'cdf6191b409e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
