"""Add mismatch table

Revision ID: fe78731f4289
Revises: a68757e06e53
Create Date: 2025-07-23 20:40:22.887062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe78731f4289'
down_revision = 'a68757e06e53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # First, add the column as nullable
    op.add_column('mismatches', sa.Column('severity', sa.String(), nullable=True))
    
    # Update existing NULL values with a default value
    op.execute("UPDATE mismatches SET severity = 'medium' WHERE severity IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('mismatches', 'severity', nullable=False)
    
    # Add other columns...
    op.add_column('mismatches', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('mismatches', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('mismatches', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('mismatches', sa.Column('owner_id', sa.Integer(), nullable=True))
    
    # Add constraints...
    op.create_index(op.f('ix_mismatches_severity'), 'mismatches', ['severity'], unique=False)
    op.create_foreign_key(None, 'mismatches', 'users', ['owner_id'], ['id'])  # Adjust table name as needed
    
    # Remove the old column
    op.drop_column('mismatches', 'detected_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mismatches', sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mismatches', type_='foreignkey')
    op.drop_index(op.f('ix_mismatches_severity'), table_name='mismatches')
    op.alter_column('mismatches', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('mismatches', 'owner_id')
    op.drop_column('mismatches', 'updated_at')
    op.drop_column('mismatches', 'created_at')
    op.drop_column('mismatches', 'details')
    op.drop_column('mismatches', 'severity')
    # ### end Alembic commands ###
